# Generated by Django 5.0.6 on 2024-06-09 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms_app', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='seats',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AddField(
            model_name='bus',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveIntegerField()),
                ('is_occupied', models.BooleanField(default=False)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bms_app.bus')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='seat',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bms_app.seat'),
        ),
    ]
